//Ryan D. 12/14/2019.
//Imports.
import java.awt.event.KeyEvent;
import java.util.Random;
import java.awt.*;
public class Decrypt extends javax.swing.JFrame {

    // Methods defined as strings.
    String EncryptedText;
    String DecryptedText;
    Encrypt callingForm;
    public Decrypt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPop = new javax.swing.JPanel();
        cmdExitPop = new javax.swing.JButton();
        cmdEnterPop = new javax.swing.JButton();
        txtOriginalPop = new javax.swing.JTextField();
        lblPassPop = new javax.swing.JLabel();
        lblEncryptedPop = new javax.swing.JLabel();
        txtEncryptedPop = new javax.swing.JTextField();
        cmdClear2Pop = new javax.swing.JButton();
        cmdClear1Pop = new javax.swing.JButton();
        lblFeedbackPop = new javax.swing.JLabel();
        lblTitlePop = new javax.swing.JLabel();
        lblImgPop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPop.setBackground(new java.awt.Color(255, 204, 204));
        pnlPop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdExitPop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cmdExitPop.setText("Exit");
        cmdExitPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitPopActionPerformed(evt);
            }
        });
        pnlPop.add(cmdExitPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 358, 65, 25));

        cmdEnterPop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cmdEnterPop.setText("Enter");
        cmdEnterPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnterPopActionPerformed(evt);
            }
        });
        pnlPop.add(cmdEnterPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 322, 65, 25));

        txtOriginalPop.setEditable(false);
        txtOriginalPop.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtOriginalPop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOriginalPopKeyPressed(evt);
            }
        });
        pnlPop.add(txtOriginalPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 275, 292, -1));

        lblPassPop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblPassPop.setText("Original:");
        pnlPop.add(lblPassPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 279, 59, -1));

        lblEncryptedPop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblEncryptedPop.setText("Encrypted:");
        pnlPop.add(lblEncryptedPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 243, -1, -1));

        txtEncryptedPop.setEditable(false);
        txtEncryptedPop.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        txtEncryptedPop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEncryptedPopKeyPressed(evt);
            }
        });
        pnlPop.add(txtEncryptedPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 239, 292, -1));

        cmdClear2Pop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cmdClear2Pop.setText("Clear");
        cmdClear2Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClear2PopActionPerformed(evt);
            }
        });
        pnlPop.add(cmdClear2Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 275, 65, 25));

        cmdClear1Pop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        cmdClear1Pop.setText("Clear");
        cmdClear1Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClear1PopActionPerformed(evt);
            }
        });
        pnlPop.add(cmdClear1Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 239, 65, 25));

        lblFeedbackPop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pnlPop.add(lblFeedbackPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 211, 376, 17));

        lblTitlePop.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblTitlePop.setText("RSA Text Decryptor");
        lblTitlePop.setInheritsPopupMenu(false);
        pnlPop.add(lblTitlePop, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 0, -1, -1));

        lblImgPop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unlock.gif"))); // NOI18N
        pnlPop.add(lblImgPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Method used for referencing the first jframe.
   public void SetParentReference(Encrypt callingProject){
        callingForm = callingProject;
    }
    
    private void txtOriginalPopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalPopKeyPressed
        String value = txtOriginalPop.getText();
        int l = value.length();
        if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE ||  evt.getKeyChar() == KeyEvent.VK_DELETE)
        // Always accept backspace and delete.
        txtOriginalPop.setEditable(true);
        else if (l < 25)
        // Accept a character if they haven't typed more than 25 characters already.
        txtOriginalPop.setEditable(true);
        else
        txtOriginalPop.setEditable(false);
    }//GEN-LAST:event_txtOriginalPopKeyPressed

    private void txtEncryptedPopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEncryptedPopKeyPressed
        String value = txtEncryptedPop.getText();
        int l = value.length();
        if (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE ||  evt.getKeyChar() == KeyEvent.VK_DELETE)
        // Always accept backspace and delete.
        txtEncryptedPop.setEditable(true);
        else if (l < 25)
        // Accept a character if they haven't typed more than 25 characters already.
        txtEncryptedPop.setEditable(true);
        else
        txtEncryptedPop.setEditable(false);
    }//GEN-LAST:event_txtEncryptedPopKeyPressed

    private void cmdEnterPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnterPopActionPerformed
        try {// Try and catch used for decrypting the key upon interaction with the enter button.
            EncryptedText = txtEncryptedPop.getText();
            callingForm.SetEncryptedText(EncryptedText);
            DecryptedText = callingForm.getDecryptedText();
            this.txtOriginalPop.setText(DecryptedText);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cmdEnterPopActionPerformed

    private void cmdExitPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitPopActionPerformed
        System.exit(0);// Program will close upon interaction.
    }//GEN-LAST:event_cmdExitPopActionPerformed

    private void cmdClear2PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClear2PopActionPerformed
        txtOriginalPop.setText(""); // Original field will clear upon interaction.
    }//GEN-LAST:event_cmdClear2PopActionPerformed

    private void cmdClear1PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClear1PopActionPerformed
        txtEncryptedPop.setText(""); // Encrypted field will clear upon interaction.
    }//GEN-LAST:event_cmdClear1PopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClear1Pop;
    private javax.swing.JButton cmdClear2Pop;
    private javax.swing.JButton cmdEnterPop;
    private javax.swing.JButton cmdExitPop;
    private javax.swing.JLabel lblEncryptedPop;
    private javax.swing.JLabel lblFeedbackPop;
    private javax.swing.JLabel lblImgPop;
    private javax.swing.JLabel lblPassPop;
    private javax.swing.JLabel lblTitlePop;
    private javax.swing.JPanel pnlPop;
    private javax.swing.JTextField txtEncryptedPop;
    private javax.swing.JTextField txtOriginalPop;
    // End of variables declaration//GEN-END:variables
}
